package de.hsos.richwps.mb.execView.dialog.components;

import de.hsos.richwps.mb.richWPS.entity.specifier.InputLiteralDataSpecifier;
import javax.swing.border.TitledBorder;

/**
 *
 * @author dalcacer
 */
public class InputLiteralData extends javax.swing.JPanel {

    private String id;
    private InputLiteralDataSpecifier specifier;

    public InputLiteralData(InputLiteralDataSpecifier specifier) {
        initComponents();
        this.specifier = specifier;
        String theidentifier = specifier.getIdentifier();
        String theabstract = specifier.getAbstract();
        String thetitel = specifier.getTitle();
        String datatype = this.specifier.getSubtype();
        //fixme
        this.id = theidentifier;
        //        this.identifier.setText(theidentifier+ "("+datatype+"):");
        this.setBorder(new TitledBorder(theidentifier + "(" + datatype + ")"));
        this.hint.setText("Hint: " + thetitel + ", " + theabstract);
    }

    public InputLiteralDataSpecifier getSpecifier() {
        return this.specifier;
    }

    public String getText() {
        return this.value.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        value = new javax.swing.JTextField();
        hint = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(400, 42));
        setLayout(new java.awt.GridBagLayout());

        value.setPreferredSize(new java.awt.Dimension(120, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(value, gridBagConstraints);

        hint.setText("Hint");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(hint, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hint;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
