package de.hsos.richwps.mb.execView.dialog.components;

import de.hsos.richwps.mb.richWPS.entity.specifier.OutputLiteralDataSpecifier;
import net.opengis.wps.x100.OutputDescriptionType;

/**
 *
 * @author dalcacer
 */
public class OutputLiteralData extends javax.swing.JPanel {
    
    private OutputLiteralDataSpecifier specifier;
    
    /**
     * Creates new form OutputsParamPanel
     */
    public OutputLiteralData(final OutputLiteralDataSpecifier specifier) {
        this.specifier=specifier;
        initComponents();
    }

    
    public OutputLiteralDataSpecifier getSpecifier(){
        return this.specifier;
    }
    
    public boolean isSelected(){
        return this.selectOutput.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selectOutput = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        selectOutput.setText("Select");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(111, 47, 168, 267);
        add(selectOutput, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JCheckBox selectOutput;
    // End of variables declaration//GEN-END:variables
}
