package de.hsos.richwps.mb.execView.dialog;

import de.hsos.richwps.mb.execView.dialog.components.InputLiteralData;
import de.hsos.richwps.mb.execView.dialog.components.InputComplexData;
import de.hsos.richwps.mb.richWPS.boundary.RichWPSProvider;
import de.hsos.richwps.mb.richWPS.entity.IInputArgument;
import de.hsos.richwps.mb.richWPS.entity.execute.ExecuteRequestDTO;
import de.hsos.richwps.mb.richWPS.entity.IInputSpecifier;
import de.hsos.richwps.mb.richWPS.entity.execute.InputComplexDataArgument;
import de.hsos.richwps.mb.richWPS.entity.execute.InputLiteralDataArgument;
import de.hsos.richwps.mb.richWPS.entity.specifier.InputComplexDataSpecifier;
import de.hsos.richwps.mb.richWPS.entity.specifier.InputLiteralDataSpecifier;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author dalcacer
 */
public class InputParameterization extends ADialogPanel {

    private List<JPanel> inputs;
    private RichWPSProvider provider;
    private ExecuteRequestDTO dto;

    /**
     * Creates new form ExecutePanel
     */
    public InputParameterization() {
        initComponents();
    }

    /**
     * Creates new form ExecutePanel
     *
     * @param provider
     * @param dto
     */
    public InputParameterization(final RichWPSProvider provider, ExecuteRequestDTO dto) {
        this.provider = provider;
        this.dto = dto;
        initComponents();
        this.inputs = new ArrayList<>();
        String selectedserver = this.dto.getEndpoint();
        String selectedprocess = this.dto.getProcessid();
        this.selectedServer.setText(selectedserver);
        this.selectedProcess.setText(selectedprocess);
        this.dto = this.provider.describeProcess(dto);
        this.showInputs();
    }

    private void showInputs() {

        for (IInputSpecifier specifier : this.dto.getInputSpecifier()) {
            if (specifier instanceof InputLiteralDataSpecifier) {
                this.inputs.add(new InputLiteralData((InputLiteralDataSpecifier) specifier));
            } else if (specifier instanceof InputComplexDataSpecifier) {
                this.inputs.add(new InputComplexData((InputComplexDataSpecifier) specifier));
            }
            //FIXME BoundingBox
        }

        GridLayout layout = new GridLayout(this.inputs.size(), 1);
        this.inputsPanel.setLayout(layout);

        for (JPanel panel : this.inputs) {
            this.inputsPanel.add(panel);
        }
    }

    @Override
    public void updateDTO() {
        HashMap<String, IInputArgument> theinputs = new HashMap<>();

        for (JPanel panel : this.inputs) {

            if (panel instanceof InputComplexData) {
                InputComplexData pan = (InputComplexData) panel;
                InputComplexDataSpecifier specifier = pan.getSpecifier();

                InputComplexDataArgument param = null;
                if (pan.isReference()) {
                    param = new InputComplexDataArgument(specifier);
                    String url = pan.getValue();
                    param.setURL(url);
                    param.setMimeType(TOOL_TIP_TEXT_KEY);
                } else {
                    throw new UnsupportedOperationException("Not implemented, yet.");
                }
                String mimetype = pan.getMimeType();

                param.setMimeType(mimetype);
                param.setEncoding(specifier.getEncodingByMimetype(mimetype));
                param.setSchema(specifier.getSchemaByMimetype(mimetype));

                theinputs.put(param.getIdentifier(), param);
            } else if (panel instanceof InputLiteralData) {
                InputLiteralData pan = (InputLiteralData) panel;
                InputLiteralDataSpecifier specifier = pan.getSpecifier();
                InputLiteralDataArgument param = new InputLiteralDataArgument(specifier, pan.getText());
                theinputs.put(param.getIdentifier(), param);
            }
            //FIXME BoundingBox
        }
        this.dto.setInputArguments(theinputs);
    }

    public ExecuteRequestDTO getDTO() {
        return this.dto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selectedServer = new javax.swing.JLabel();
        selectedProcess = new javax.swing.JLabel();
        inputsPanelScrollPane = new javax.swing.JScrollPane();
        inputsPanel = new javax.swing.JPanel();
        selectedServerLabel = new javax.swing.JLabel();
        selectedProcessLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        selectedServer.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(selectedServer, gridBagConstraints);

        selectedProcess.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(selectedProcess, gridBagConstraints);

        inputsPanelScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Inputs"));
        inputsPanelScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        inputsPanelScrollPane.setPreferredSize(new java.awt.Dimension(700, 300));

        inputsPanel.setPreferredSize(new java.awt.Dimension(700, 300));
        inputsPanel.setLayout(new java.awt.BorderLayout());
        inputsPanelScrollPane.setViewportView(inputsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(inputsPanelScrollPane, gridBagConstraints);

        selectedServerLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        selectedServerLabel.setLabelFor(selectedServer);
        selectedServerLabel.setText("Server:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(selectedServerLabel, gridBagConstraints);

        selectedProcessLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        selectedProcessLabel.setLabelFor(selectedProcess);
        selectedProcessLabel.setText("Process:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(selectedProcessLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputsPanel;
    private javax.swing.JScrollPane inputsPanelScrollPane;
    private javax.swing.JLabel selectedProcess;
    private javax.swing.JLabel selectedProcessLabel;
    private javax.swing.JLabel selectedServer;
    private javax.swing.JLabel selectedServerLabel;
    // End of variables declaration//GEN-END:variables

}
