
package de.hsos.richwps.mb.execView.dialog;

import de.hsos.richwps.mb.richWPS.entity.execute.ExecuteRequestDTO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author dalcacer
 */
public class SeverSelection extends ADialogPanel {

    private List<String> remotes;
    private ExecuteRequestDTO dto;

    /**
     * Creates new form SeverSelection
     */
    public SeverSelection() {
        initComponents();
        this.remotes = new ArrayList<String>();
        this.init();
    }

    public SeverSelection(List<String> wpsurls, ExecuteRequestDTO dto) {
        this.remotes = wpsurls;
        this.dto = dto;
        this.initComponents();
        this.init();
    }

    private void init() {
        this.serverSelectionBox.removeAllItems();
        for (String s : this.remotes) {
            this.serverSelectionBox.addItem(s);
        }
    }

    @Override
    public void updateDTO() {
        this.dto = new ExecuteRequestDTO();
        this.dto.setEndpoint((String) this.serverSelectionBox.getSelectedItem());
    }

    @Override
    public ExecuteRequestDTO getDTO() {
        return dto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        serverSelectionLabel = new javax.swing.JLabel();
        serverSelectionBox = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        serverSelectionLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        serverSelectionLabel.setLabelFor(serverSelectionBox);
        serverSelectionLabel.setText("Server:");
        serverSelectionLabel.setName("serverSelectionLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(serverSelectionLabel, gridBagConstraints);

        serverSelectionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        serverSelectionBox.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(serverSelectionBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox serverSelectionBox;
    private javax.swing.JLabel serverSelectionLabel;
    // End of variables declaration//GEN-END:variables

}
