
package de.hsos.richwps.mb.execView.dialog;

import de.hsos.richwps.mb.richWPS.entity.execute.ExecuteRequestDTO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author dalcacer
 */
public class SeverSelection extends ADialogPanel {

    private List<String> remotes;
    private ExecuteRequestDTO dto;

    /**
     * Creates new form SeverSelection
     */
    public SeverSelection() {
        initComponents();
        this.remotes = new ArrayList<String>();
        this.init();
    }

    public SeverSelection(List<String> wpsurls, ExecuteRequestDTO dto) {
        this.remotes = wpsurls;
        this.dto = dto;
        this.initComponents();
        this.init();
    }

    private void init() {
        this.serverSelectionBox.removeAllItems();
        for (String s : this.remotes) {
            this.serverSelectionBox.addItem(s);
        }
    }

    @Override
    public void updateDTO() {
        this.dto.setEndpoint((String) this.serverSelectionBox.getSelectedItem());
    }

    @Override
    public ExecuteRequestDTO getDTO() {
        return dto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        serverSelectionBox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel1.setLabelFor(serverSelectionBox);
        jLabel1.setText("Server:");
        jLabel1.setName("serverSelectionLabel"); // NOI18N
        add(jLabel1);

        serverSelectionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(serverSelectionBox);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox serverSelectionBox;
    // End of variables declaration//GEN-END:variables

}
