package de.hsos.richwps.mb.app.view.dialogs.components.inputforms;

import de.hsos.richwps.mb.richWPS.entity.impl.descriptions.OutputComplexDataDescription;
import net.opengis.wps.x100.ComplexDataDescriptionType;

/**
 *
 * @author dalcacer
 */
public class OutputComplexForm extends javax.swing.JPanel {

    private OutputComplexDataDescription description;

    private String id;
    private ComplexDataDescriptionType[] subtypes_;

    /**
     * Creates new form OutputsParamPanel
     *
     * @param description
     */
    public OutputComplexForm(OutputComplexDataDescription description) {
        initComponents();
        this.description = description;

        //SupportedComplexDataType type = description.getComplexOutput();
        String theidentifier = description.getIdentifier();
        String theabstract = description.getAbstract();
        String thetitel = description.getTitle();

        this.selectType.removeAllItems();

        for (java.util.List type : description.getTypes()) {
            String amimetype = (String) type.get(OutputComplexDataDescription.mimetype_IDX);
            String aschema = (String) type.get(OutputComplexDataDescription.schema_IDX);
            String aencoding = (String) type.get(OutputComplexDataDescription.encoding_IDX);
            String line = "";

            if (description.isDefaultType(type)) {
                line = "<html><b>" + amimetype + "<br/>Schema: " + aschema + "<br/>Encoding: " + aencoding + "</b></html>";
                this.selectType.addItem(line);
                this.selectType.setSelectedItem(line);
            } else {
                line = "<html>" + amimetype + "<br/>Schema: " + aschema + "<br/>Encoding: " + aencoding + "</html>";
                this.selectType.addItem(line);
            }
        }

        //FIXME
        this.id = theidentifier;
        //this.identifier.setText(theidentifier);

        //this.setBorder(new TitledBorder(theidentifier));
        this.titleValue.setText(thetitel);
        this.abstractValue.setText(theabstract);
    }

    /**
     *
     * @return
     */
    public OutputComplexDataDescription getDescription() {
        return this.description;
    }

    /**
     *
     * @return
     */
    public boolean isSelected() {
        return this.selectOutput.isSelected();
    }

    public void setSelected() {
        this.selectOutput.setSelected(true);
    }

    public void setUnselected() {
        this.selectOutput.setSelected(false);
    }

    /**
     *
     * @return
     */
    public java.util.List getType() {
        int idx = this.selectType.getSelectedIndex();
        return description
                .getTypes().get(idx);
    }

    /**
     *
     * @return
     */
    public boolean asReference() {
        return this.selectAsReference.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleValue = new javax.swing.JTextArea();
        abstractLabel = new javax.swing.JLabel();
        abstractValue = new javax.swing.JTextArea();
        typeLabel = new javax.swing.JLabel();
        selectType = new javax.swing.JComboBox();
        selectAsReference = new javax.swing.JCheckBox();
        selectStore = new javax.swing.JCheckBox();
        selectOutput = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        setMinimumSize(new java.awt.Dimension(500, 200));
        setPreferredSize(new java.awt.Dimension(500, 250));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(5, 2, -400, 0));

        titleLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        titleLabel.setText("Title:");
        add(titleLabel);

        titleValue.setEditable(false);
        titleValue.setBackground(java.awt.SystemColor.control);
        titleValue.setColumns(20);
        titleValue.setLineWrap(true);
        titleValue.setRows(2);
        titleValue.setMinimumSize(new java.awt.Dimension(250, 32));
        titleValue.setPreferredSize(new java.awt.Dimension(300, 32));
        add(titleValue);

        abstractLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        abstractLabel.setText("Abstract:");
        add(abstractLabel);

        abstractValue.setEditable(false);
        abstractValue.setBackground(java.awt.SystemColor.control);
        abstractValue.setColumns(20);
        abstractValue.setLineWrap(true);
        abstractValue.setRows(2);
        abstractValue.setMinimumSize(new java.awt.Dimension(250, 32));
        abstractValue.setPreferredSize(new java.awt.Dimension(300, 32));
        add(abstractValue);

        typeLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        typeLabel.setText("Type:");
        add(typeLabel);

        selectType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectType.setPreferredSize(new java.awt.Dimension(450, 50));
        add(selectType);

        selectAsReference.setSelected(true);
        selectAsReference.setText("As Reference");
        selectAsReference.setEnabled(false);
        add(selectAsReference);

        selectStore.setText("Store");
        selectStore.setEnabled(false);
        add(selectStore);

        selectOutput.setText("Select");
        add(selectOutput);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstractLabel;
    private javax.swing.JTextArea abstractValue;
    private javax.swing.JCheckBox selectAsReference;
    private javax.swing.JCheckBox selectOutput;
    private javax.swing.JCheckBox selectStore;
    private javax.swing.JComboBox selectType;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextArea titleValue;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
