package de.hsos.richwps.mb.app.view.dialogs.components.inputforms;

import de.hsos.richwps.mb.richWPS.entity.impl.descriptions.OutputLiteralDataDescription;

/**
 *
 * @author dalcacer
 * @version 0.0.3
 */
public class OutputLiteralForm extends javax.swing.JPanel {

    private OutputLiteralDataDescription description;

    /**
     * Creates new form OutputLiteralData
     *
     * @param description
     */
    public OutputLiteralForm(final OutputLiteralDataDescription description) {
        this.description = description;
        initComponents();

        //SupportedComplexDataType type = description.getComplexOutput();
        String theidentifier = description.getIdentifier();
        String theabstract = description.getAbstract();
        String thetitel = description.getTitle();

        this.titleValue.setText(thetitel);

        this.abstractValue.setText(theabstract);
    }

    /**
     *
     * @return
     */
    public OutputLiteralDataDescription getDescription() {
        return this.description;
    }

    /**
     *
     * @return
     */
    public boolean isSelected() {
        return this.selectOutput.isSelected();
    }

    public void setSelected() {
        this.selectOutput.setSelected(true);
    }

    public void setUnselected() {
        this.selectOutput.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleValue = new javax.swing.JTextArea();
        abstractLabel = new javax.swing.JLabel();
        abstractValue = new javax.swing.JTextArea();
        selectOutput = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        setMinimumSize(new java.awt.Dimension(500, 200));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 200));
        setLayout(new java.awt.GridLayout(3, 2, -300, 0));

        titleLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        titleLabel.setLabelFor(titleValue);
        titleLabel.setText("Title:");
        add(titleLabel);

        titleValue.setEditable(false);
        titleValue.setBackground(java.awt.SystemColor.control);
        titleValue.setColumns(20);
        titleValue.setLineWrap(true);
        titleValue.setRows(2);
        titleValue.setMinimumSize(new java.awt.Dimension(250, 32));
        titleValue.setPreferredSize(new java.awt.Dimension(300, 32));
        add(titleValue);

        abstractLabel.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        abstractLabel.setLabelFor(abstractValue);
        abstractLabel.setText("Abstract:");
        add(abstractLabel);

        abstractValue.setEditable(false);
        abstractValue.setBackground(java.awt.SystemColor.control);
        abstractValue.setColumns(20);
        abstractValue.setLineWrap(true);
        abstractValue.setRows(2);
        abstractValue.setMinimumSize(new java.awt.Dimension(250, 32));
        abstractValue.setPreferredSize(new java.awt.Dimension(300, 32));
        add(abstractValue);

        selectOutput.setText("Select");
        add(selectOutput);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstractLabel;
    private javax.swing.JTextArea abstractValue;
    private javax.swing.JCheckBox selectOutput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextArea titleValue;
    // End of variables declaration//GEN-END:variables
}
