package de.hsos.richwps.mb.execView.dialog.components.renderer;

/**
 *
 * @author dalcacer
 */
public class FeatureCollectionRenderer extends javax.swing.JPanel {

    /**
     * Creates new form FeatureCollectionRenderer
     */
    public FeatureCollectionRenderer() {
        initComponents();
    }

    /**
     * Creates new form FeatureCollectionRenderer
     */
    public FeatureCollectionRenderer(String reference) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Soon!");
        add(jLabel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
