package de.hsos.richwps.mb.ui.dialogs.components.renderer;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.math.BigInteger;
import java.util.List;
import javax.swing.border.TitledBorder;
import net.opengis.ows.x11.BoundingBoxType;
import net.opengis.wps.x100.OutputDataType;

/**
 *
 * @author caduevel
 */
public class BoundingBoxResultRenderer extends javax.swing.JPanel {
    String clipValue;
    
    /**
     * Creates new form FeatureCollectionRenderer
     */
    public BoundingBoxResultRenderer() {
        initComponents();
    }

    /**
     * Creates new form FeatureCollectionRenderer
     * @param identifier
     * @param bbData
     */
    //public BoundingBoxResultRenderer(String identifier, String value) {
    public BoundingBoxResultRenderer(String identifier, BoundingBoxType bbData) {
        
        initComponents();
        this.setBorder(new TitledBorder(identifier));
        
        String crs = bbData.getCrs();
        String dimensions = bbData.getDimensions().toString();
        String lowerCorner = bbData.getLowerCorner().toString();
        String upperCorner = bbData.getUpperCorner().toString();
        
        this.clipValue = bbData.xmlText();
        
        this.crsVal.setText(crs);
        this.dimmensionVal.setText(dimensions);
        this.lowerCornerVal.setText(lowerCorner);
        this.upperCornerVal.setText(upperCorner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        crsVal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dimmensionVal = new javax.swing.JLabel();
        copyToClipBoard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lowerCornerVal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        upperCornerVal = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(320, 160));

        jLabel1.setText("CRS:");

        crsVal.setText("EPSG:****");

        jLabel3.setText("Dimmension:");

        dimmensionVal.setText("42");

        copyToClipBoard.setText("Copy To Clipboard");
        copyToClipBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipBoardActionPerformed(evt);
            }
        });

        jLabel5.setText("LowerCorner(X Y):");

        lowerCornerVal.setText("-4,2 -1,3");

        jLabel7.setText("UpperCorner(X Y):");

        upperCornerVal.setText("3,7 4,2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(copyToClipBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lowerCornerVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperCornerVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dimmensionVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crsVal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crsVal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dimmensionVal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upperCornerVal)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lowerCornerVal)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyToClipBoard)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");
    }// </editor-fold>//GEN-END:initComponents

    private void copyToClipBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipBoardActionPerformed
    StringSelection stringSelection = new StringSelection(clipValue);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_copyToClipBoardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyToClipBoard;
    private javax.swing.JLabel crsVal;
    private javax.swing.JLabel dimmensionVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lowerCornerVal;
    private javax.swing.JLabel upperCornerVal;
    // End of variables declaration//GEN-END:variables
}
