package de.hsos.richwps.mb.ui.dialogs.components.renderer;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author dalcacer
 * @version 0.0.2
 */
public class ExceptionRenderer extends javax.swing.JPanel {

    /**
     * Creates new form FeatureCollectionRenderer
     */
    public ExceptionRenderer() {
        initComponents();
    }

    /**
     * Creates new form FeatureCollectionRenderer
     *
     * @param exception
     */
    public ExceptionRenderer(final String exception) {
        initComponents();
        this.exceptionPane.setText(exception);
        this.exceptionPane.setContentType("text/plain");
        this.exceptionPane.setEditable(false);
        this.exceptionPane.setVisible(true);
        
        this.exceptionPane.validate();
        this.exceptionScrollPane.setViewportView(this.exceptionPane);
        this.exceptionScrollPane.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        exceptionScrollPane = new javax.swing.JScrollPane();
        exceptionPane = new javax.swing.JTextPane();
        copyToClipBoard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setLayout(new java.awt.GridBagLayout());

        exceptionScrollPane.setBorder(null);
        exceptionScrollPane.setMinimumSize(new java.awt.Dimension(500, 500));
        exceptionScrollPane.setPreferredSize(new java.awt.Dimension(500, 550));

        exceptionPane.setBorder(null);
        exceptionPane.setMinimumSize(new java.awt.Dimension(650, 400));
        exceptionPane.setPreferredSize(new java.awt.Dimension(650, 400));
        exceptionScrollPane.setViewportView(exceptionPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(exceptionScrollPane, gridBagConstraints);

        copyToClipBoard.setText("Copy To Clipboard");
        copyToClipBoard.setMaximumSize(new java.awt.Dimension(110, 32));
        copyToClipBoard.setMinimumSize(new java.awt.Dimension(110, 32));
        copyToClipBoard.setPreferredSize(new java.awt.Dimension(110, 32));
        copyToClipBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipBoardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(copyToClipBoard, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel1.setText("A server-side exception occured.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void copyToClipBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipBoardActionPerformed
        StringSelection stringSelection = new StringSelection(exceptionPane.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_copyToClipBoardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyToClipBoard;
    private javax.swing.JTextPane exceptionPane;
    private javax.swing.JScrollPane exceptionScrollPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
